import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.scss";
import "../styles/base.scss";
import { ThemeProvider } from "next-themes";
import { ClientProvider } from "@/components/clientProvider/clientProvider";
import { ToastProvider } from "@/components/toastProvider/toastProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "AI Chat Engine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ClientProvider>
            {children}
            <ToastProvider />
          </ClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
